sudo: false
language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.2
  - 1.8.1
otp_release:
  - 18.3
  - 19.3
  - 20.3
  - 21.2
script:
  - mix deps.compile
  - mix compile --warnings-as-errors
  - mix test
  - ./test/smoke_test.sh
  - ./test/check_formatted.sh
after_script:
  - MIX_ENV=test mix inch.report
matrix:
  allow_failures:
  - elixir: 1.4.5
  exclude:
  - elixir: 1.4.5
    otp_release: 21.2
  - elixir: 1.5.3
    otp_release: 21.2
  - elixir: 1.6.6
    otp_release: 18.3
  - elixir: 1.7.2
    otp_release: 18.3
  - elixir: 1.8.1
    otp_release: 18.3
  - elixir: 1.8.1
    otp_release: 19.3
